---
name:
  type: string
  required: true
organization:
  type: string
  required: true
synthetic:
  type: boolean
  required: true
baseURL:
  type: string
  required: true
contacts:
  - name:
      type: string
      required: true
    email:
      type: string
      required: true
headers:
  - name:
      type: string
      required: true
    value:
      type: string
      required: true
params:
  - name:
      type: string
      required: true
    value:
      type: string
      required: true
